apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: default  # or your specific namespace
data:
  .dockerconfigjson: |-
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "vsrekul",
          "password": "Vijay@100*",
          "auth": "dm9yZWVrdWw6VklqYXAwMDAq"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
